language: ruby

rvm:
  - 2.3.1
  - 2.4.0

install: bundle install --without="development system_tests"
script:
  - bundle exec rake
env:
  - PUPPET_VERSION=4.10
  - PUPPET_VERSION=5.5

branches:
  only:
    - master
    - develop

